### ISSUE TITLE
check completeness of daily AUX data 

### ISSUE THREAD

**Issue by yannick-peyrotau** [reprocessing-reference/preparation#12]
Considering the shortcoming time for the Reprocessing Configuration Baseline delivery the check is not a priority. Nevertheless, the scope of this procurement is to prepare a baseline that will be successful during the Reprocessing Operations, for this reason the completeness check is one of the scopes of the procurement. 

Could you confirm that for the moment there are no discrepancies detected? CS : Yes, not find at the moment
What is the evaluated effort to build a software check on the date continuity? CS : The effort is not the problem, but we need this task after 28/10/2020.

**During the meeting:** ESA doesn’t need the Excel file on October, but need to find missing AUX to ask and find them during the time of project to have a complete database. CS has to generate it (by script) and not to make it by hand. This script shall be complete before 07/12/2020.

**Comment by cbouzina** [comment]
What should be ready for 07dec2020 ? the script or the data sets ?

**Comment by yannick-peyrotau** [comment]
Both. The 07dec is the max date I want to send it to Bogdana.

**Comment by cbouzina** [comment]
I have added this test with script in the verification plan. I will prepare the scripts, but which language should be used ? Python or Shell ?

**Comment by yannick-peyrotau** [comment]
You can choose, it is for internal CS needs

**Comment by cbouzina** [comment]
S1 and S2 scripts are ready to be tested.
