### ISSUE TITLE
S3 MWR AUX files

### ISSUE THREAD

**Issue by cbouzina** [reprocessing-reference/preparation#13]
The selection rules for the following S3 MWR AUX files:
MW_1_SLC_AX, MW___STD_AX, MW_1_NIR_AX, MW_1_DNB_AX, MW_1_MON_AX
cannot be found in the provided documentation,
but maybe they are not necessary for reprocessing activity ?

**Comment by cbouzina** [comment]
These AUX files are delivered so this confirms that they exist and can be used for reprocessing activity.
But the associated selection rules are missing from documentation.

**Comment by BogdanaTsonevska** [comment]
Email sent to the Sentinel 3 ESA Technical officer

**Comment by cbouzina** [comment]
ESA provided the necessary document yesterday. This action is closed.
