### ISSUE TITLE
Inputs missing from S2-MPC

### ISSUE THREAD

**Issue by cbouzina** [reprocessing-reference/preparation#14]
GIPP SPAMOD: (mail sent to S2-MPC on 15oct2020)

It seems 2 SPAMOD have been replaced by only only one (which is normally impossible).
Maybe the SPAMOD for S2A launch was bad (which is probable).
In such case, the following 2 SPAMOD contents should be identical:
S2A_OPER_GIP_SPAMOD_MPC__20150731T092205_V20150703T000000_21000101T000000_B00
S2A_OPER_GIP_SPAMOD_MPC__20160208T132500_V20150622T000000_20150901T020000_B00
Please check.

GIPP R2SWIR: (mail sent to S2-MPC on 15oct2020)

Concerning S2A on-board pixel reselection on 20150819 11:26, there are GIPP R2SWIR:
S2A_OPER_GIP_R2SWIR_MPC__20150814T133900_V20150819T112600_21000101T000000_B00
S2A_OPER_GIP_R2SWIR_MPC__20150814T133900_V20150819T120000_21000101T000000_B00
Which one should be used ?

What is the following R2SWIR GIPP, knowing that nothing happened on board on 20160223  ?
S2A_OPER_GIP_R2SWIR_MPC__20160304T100014_V20160223T230345_21000101T000000_B00 

GIPP R2ABCA and R2EQOG: (mail sent to S2-MPC on 20oct2020)

The lists of R2ABCA and R2EQOG GIPP file names for S2A and S2B have been corrected (by Ouahid and Catherine). 
The corresponding GIPP files should be generated with correct file name by S2-MPC.

**Comment by BogdanaTsonevska** [comment]
email sent to ESA TO S2-MPC

**Comment by cbouzina** [comment]
The mail from S2MPC on 24nov2020 replied to all points except the last one.
The last point concerns the R2ABCA and R2EQOG GIPP files, for which the file names should be corrected.

**Comment by cbouzina** [comment]
New question for S2-MPC:
In the DB is found S2A_OPER_GIP_R2SWIR_MPC__20160118T123902_V20151125T000000_21000101T000000_B00.TGZ
This GIPP is not referenced anywhere.
Can you confirm that this GIPP should be used in reprocessing please ?

**Comment by BogdanaTsonevska** [comment]
email send to S2 MPC T.O on 1/02. Today I propose to contact directly the MPC with the T.O. To gain some time could you please ask the MPC directly as they are CS Group?

**Comment by cbouzina** [comment]
That is why I had assigned Yannick ;-)

**Comment by cbouzina** [comment]
Reply from S2-MPC today:   This R2SWIR GIPP should be used.

**Comment by yannick-peyrotau** [comment]
Reply from S2-MPC the 12/02 : This R2SWIR GIPP should be used.

**Comment by cbouzina** [comment]
On 09 june 2021, ESA provided S2-PDGS-MPC-TN-20015.
This TN finally details all the necessary actions from S2-MPC to be performed before reprocessing campaign.
They are now well understood but not achieved. The necessary adapted GIPP files are not yet created.
There is still one possible question which is not addressed in the TN20015:
Are you sure about the validity starts of the existing R2EOB2, R2SWIR and R2DEPI GIPP files ?

**Comment by BogdanaTsonevska** [comment]
Do you want me to ask this question to Valentina or internally you will manage to obtain it?  
Regards,
Bogdana

**Comment by yannick-peyrotau** [comment]
Internally they are checking this 3 files. (this is linked to history of damaged pixels and reselectionned)
It is possible that some of them are too much.

We will make a meeting internally on Monday before asking to valentina.

**Comment by cbouzina** [comment]
The last missing S2 GIPP files have not yet been delivered.

**Comment by cbouzina** [comment]
Still no delivery of the last S2 GIPP files.
Bogdana please, could you send a reminder to Valentina ?
S2-MPC prime is not CS anymore but ACRI.

**Comment by cbouzina** [comment]
All GIPP files for reprocessing campaign have been provided by S2-MPC.
