### ISSUE TITLE
Document 2 Analysis the trade-off between storing products and calculating them on the fly

### ISSUE THREAD

**Issue by BogdanaTsonevska** [reprocessing-reference/preparation#15]
you expressed as blocking for the Reprocessing the Anomaly on FEE data read and converted from HKTM into L0C. 
Could you provide more information. Context, Cause, Description is there anything put in place to revolve it (palietif in french), are there actions ongoing?

**Comment by cbouzina** [comment]
This is not blocking. This is just indicating that the L0 quality is not yet optimal, so that when this anomaly in IPF will be solved (IPF team knows all the details about it), the L0 data will have to be reprocessed.

**Comment by BogdanaTsonevska** [comment]
Thanks Catherine
