### ISSUE TITLE
orbits

### ISSUE THREAD

**Issue by BogdanaTsonevska** [reprocessing-reference/preparation#16]
Dear Catherine, 

Orbit data must be the best quality (precise for S1 and S3, restituted for S2) from Copernicus POD service.
=>Could you please confirm that the POD files are going to be considered in the Reprocessing Data Configuration as for the weather files?
From what you find are there any particularity that I should start search information from third parties ( POD services, etc)?  
Regards,
Bogdana

**Comment by cbouzina** [comment]
Yes, I confirm. All OK. No foreseen problem at the moment.

**Comment by cbouzina** [comment]
There is no S2 restituted orbit RESORB_OPOD files in the data base.

**Comment by BogdanaTsonevska** [comment]
For my understanding  RESORB data are not needed for the the reprocessing, could you confirm?

**Comment by cbouzina** [comment]
I confirm the opposite : RESORB_OPOD is mandatory for S2 reprocessing :-) as written in the User Manual.

**Comment by BogdanaTsonevska** [comment]
OK, email send to S2 T.O. in order to verify how to obtain them.

**Comment by BogdanaTsonevska** [comment]
From:	"Olivier Colin" <Olivier.Colin@esa.int>
To:	"Bogdana Tsonevska" <bogdana.tsonevska@esa.int>
Cc:	"Roberto De Bonis" <Roberto.De.Bonis@esa.int>
Date:	26/01/2021 15:31
Subject:	Re: [reprocessing-reference/preparation] orbits (#16)



btw, these POD orbits have never ever been used in the processing to date, not even to test/validate what would come out in terms of geometric quality.
The use of POD in S2 was always foreseen only as a possible solution in case of contingency of the on-board GPS, btw only specific TBD types of contingencies as if GPS would drastically fail then even POD would have difficulty to generate that file without major changes.
The interface for POD products in IPF is there just for this kind of contingency. when IPF uses the POD input, it does not use any longer the GPS/AOCS info in the raw data.
=> Could you please correct the UM accordingly to the informations from Olivier Collin please, if you don't have objections of course.

**Comment by cbouzina** [comment]
OK, but I think Valentina Boccia or Ferran Gascon should decide on this, because it regards the quality of the reprocessed products.

**Comment by BogdanaTsonevska** [comment]
Could you please proved me with the technical justification why the quality of the products are improved if the POD orbits are used?

**Comment by cbouzina** [comment]
This is largely justified in the very complete information provided in 
https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-2-msi/pod
If it was not justified, Copernicus would not pay for such service.

However, I did as you wish: Sentinel-2 POD orbits are now out of scope for this activity.

**Comment by BogdanaTsonevska** [comment]
Thank you for the provided information. Nevertheless, this information doesn't show that the files were used in the past for the Reprocessing or processing activities. To use these files as you suggested in K.O. means to introduce unnecessary risk for the Reprocessing activities such as non-compatibility, non-conformance etc. ESA GS operations decision is not to use them because the files were meant to be used only for contingency with on-board GPS and they were never been used before in operation.
