### ISSUE TITLE
S3 missing files

### ISSUE THREAD

**Issue by BogdanaTsonevska** [reprocessing-reference/preparation#19]
Dear Catherine S3A_SR___CHDRAX_20160216T000000_20991231T235959_20200312T120000___________________MPC_O_AL_006.SEN3 is missing ?
S3B_SR___CHDRAX_20180425T000000_20991231T235959_20200312T120000___________________MPC_O_AL_005.SEN3 is missing ?
Could you please tell me if they are missing from the LTA or from the list provided by the PDGS, so I can contact the S3 ESA TO ?
Regards
Bogdana

**Comment by cbouzina** [comment]
They are missing from the list in lta-STM.txt

**Comment by BogdanaTsonevska** [comment]
email sent to ESA T.O.

**Comment by cbouzina** [comment]
SL_2_F2N_AX files are missing, but the documentation says that the IPF does not use them until now.
This is confirmed by ESA so they are put out of scope.

**Comment by cbouzina** [comment]
Dear Bogdana, 
usually a new version of SR___CHDNAX is always issued with a new version of SR___CHDRAX, but for the last version only the CHDNAX are available, so could you confirm that 
S3A_SR___CHDRAX_20160216T000000_20991231T235959_20200312T120000___________________MPC_O_AL_006.SEN3 
S3B_SR___CHDRAX_20180425T000000_20991231T235959_20200312T120000___________________MPC_O_AL_005.SEN3
are not necessary please ?  
For the delivery of next week, I write "SR___CHDRAX are not available".

**Comment by BogdanaTsonevska** [comment]
email send to ESA T.O.
OK for the delivery for next week.

**Comment by cbouzina** [comment]
Dear Bogdana, 
I am still confused about this topic, could you please confirm ESA decision concernig SR_CHDRAX :
"SR___CHDRAX are not available and not necessary for now"
or
"S3A_SR___CHDRAX_20160216T000000_20991231T235959_20200312T120000___________________MPC_O_AL_006.SEN3
and S3B_SR___CHDRAX_20180425T000000_20991231T235959_20200312T120000___________________MPC_O_AL_005.SEN3
are missing and should be provided by ESA"

**Comment by cbouzina** [comment]
Dear Bogdana, 
after further investigation, it seems that indeed SR_CHDRAX are not used in PDGS and not mentioned in S3 SRAL products, so probably they are not generated anymore by S3 MPC. So I guess we can keep the statement "SR___CHDRAX are not available and not necessary for now", and remove old SR_CHDRAX files from the data base Do you agree ?

**Comment by BogdanaTsonevska** [comment]
Dear Catherine,
Yes, I agree.
Thank you.
Regards,
Bogdana

**Comment by cbouzina** [comment]
List of missing ADF for Sentinel-3 :::

S3B_SR_1_CONMAX_20180425T000000_20991231T235959_20200722T120000___________________MPC_O_AL_004

S3__SL_2_LSTWAX_20000101T000000_20991231T235959_20151214T120000___________________MPC_O_AL_001
S3A_SL_2_FRPTAX_20160216T000000_20991231T235959_20191115T120000___________________MPC_O_AL_003
S3A_SL_2_LSTEAX_20160216T000000_20991231T235959_20170116T120000___________________MPC_O_AL_002
S3__SL_2_LSTVAX_20000101T000000_20991231T235959_20151214T120000___________________MPC_O_AL_001
S3A_SL_2_LSTCAX_20160216T000000_20991231T235959_20190215T120000___________________MPC_O_AL_003
S3__SL_2_LSTBAX_20000101T000000_20991231T235959_20151214T120000___________________MPC_O_AL_001
S3B_SL_2_LSTEAX_20180425T000000_20991231T235959_20180409T120000___________________MPC_O_AL_001
S3B_SL_2_FRPTAX_20180425T000000_20991231T235959_20191115T120000___________________MPC_O_AL_002
S3B_SL_2_LSTCAX_20180425T000000_20991231T235959_20190215T120000___________________MPC_O_AL_002

S3B_OL_1_INS_AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002
S3B_OL_1_CAL_AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002
S3B_OL_1_EO__AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002

S3A_OL_1_MCHDAX_20160216T000000_20991231T235959_20170120T120000___________________MPC_O_AL_003
S3__SY_2_AODCAX_20000101T000000_20991231T235959_20180704T120000___________________MPC_O_AL_001

Naceur, could you please check that these ADF are still missing in the data base ?

**Comment by cbouzina** [comment]
The confirmed list of missing ADF for Sentinel-3 is :::

S3__SL_2_LSTWAX_20000101T000000_20991231T235959_20151214T120000___________________MPC_O_AL_001
S3A_SL_2_FRPTAX_20160216T000000_20991231T235959_20191115T120000___________________MPC_O_AL_003
S3A_SL_2_LSTEAX_20160216T000000_20991231T235959_20170116T120000___________________MPC_O_AL_002
S3__SL_2_LSTVAX_20000101T000000_20991231T235959_20151214T120000___________________MPC_O_AL_001
S3A_SL_2_LSTCAX_20160216T000000_20991231T235959_20190215T120000___________________MPC_O_AL_003
S3__SL_2_LSTBAX_20000101T000000_20991231T235959_20151214T120000___________________MPC_O_AL_001
S3B_SL_2_LSTEAX_20180425T000000_20991231T235959_20180409T120000___________________MPC_O_AL_001
S3B_SL_2_FRPTAX_20180425T000000_20991231T235959_20191115T120000___________________MPC_O_AL_002
S3B_SL_2_LSTCAX_20180425T000000_20991231T235959_20190215T120000___________________MPC_O_AL_002

S3B_OL_1_INS_AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002
S3B_OL_1_CAL_AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002
S3B_OL_1_EO__AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002

S3A_OL_1_MCHDAX_20160216T000000_20991231T235959_20170120T120000___________________MPC_O_AL_003
S3__SY_2_AODCAX_20000101T000000_20991231T235959_20180704T120000___________________MPC_O_AL_001

**Comment by cbouzina** [comment]
mail from bogdana.tsonevska@esa.int on 10/11/2021:

[01:08] Nigel Houghton 
S3B_OL_1_INS_AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002.SEN3.zip
S3B_OL_1_CAL_AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002.SEN3.zip
S3B_OL_1_EO_AX_20180425T000000_20180617T235959_20180621T120000__________________MPC_O_AL_002.SEN3.zip 

These 3 products are version 002 and this version was never used operationally (Jordi tells me version 001 is the pre-launch version whereas version 003 is at the end of the commissioning phase) so these products should probably never been in the LTA if there are of no use operationally. I would investigate why these 002 products re even in the list of products expected to be in the LTA. They were not in the legacy LTA either. This should be documented somewhere. 
They have now been archived in ALTA having been taken from the S3 MPC but I suspect we may have to delete them.

**Comment by cbouzina** [comment]
All files have been retrieved on ACRI LTA.
