### ISSUE TITLE
How much time CS have when IPF update appear to update auxip catalog ?

### ISSUE THREAD

**Issue by yannick-peyrotau** [reprocessing-reference/preparation#20]

**Comment by cbouzina** [comment]
The frequency of the database updates through the retrieval of new files on LTA servers is monthly.
The retrieval of CAMS and ECMWF analysis files is performed weekly.
The retrieval of CAMS and ECMWF reanalysis files is performed in January and July every year.

**Comment by cbouzina** [comment]
IPF update is done.
