### ISSUE TITLE
S3 aux selection rules

### ISSUE THREAD

**Issue by cbouzina** [reprocessing-reference/preparation#22]
The selection rule for the following AUX types is not found in documentation:

SL_2_SXPAAX, SL_2_PLFMAX, SL_2_FXPAAX, SL_2_CFM_AX, SL_2_PCPAAX, SL_2_PCPFAX
SL_1_PCPBAX
SL_1_PLTBAX
OL_2_PCPBAX
OL_2_PLTBAX
SL_2_PCPBAX
SL_2_PLTBAX
OL_1_PCPBAX
OL_1_PLTBAX
SY_2_PCPBAX
SY_2_PLTBAX
SY_2_CVPBAX
SY_2_PVPBAX
SY_2_CVSBAX
SY_2_PVSBAX

**Comment by BogdanaTsonevska** [comment]
email sent to ESA S3 TO

**Comment by cbouzina** [comment]
SL_1_PCPBAX
SL_1_PLTBAX
OL_2_PCPBAX
OL_2_PLTBAX
SL_2_PCPBAX
SL_2_PLTBAX
OL_1_PCPBAX
OL_1_PLTBAX
SY_2_PCPBAX
SY_2_PLTBAX
SY_2_CVPBAX
SY_2_PVPBAX
SY_2_CVSBAX
SY_2_PVSBAX
are AUX types for the Browser Products generation. They are out of scope (mail from ESA on 18nov2020).

**Comment by cbouzina** [comment]
The selection rule for the following S3 AUX types is still missing:
SL_2_SXPAAX, SL_2_PLFMAX, SL_2_FXPAAX, SL_2_CFM_AX, SL_2_PCPAAX, SL_2_PCPFAX

**Comment by cbouzina** [comment]
S3MPC.ACR.FRP.005 - i1r1 - SLSTR L2 Interface Control Document, provided on 02dec2020 by ESA, gives the missing selection rules, except for SL_2_PCPAAX. However, this aux type seems to be for NRT mode only. TBC

**Comment by cbouzina** [comment]
Confirmed by ESA: SL_2_PCPAAX is for NRT mode only, so it is out of scope.
