### ISSUE TITLE
S1 Some AUXIP PP1 CAL INS missing 

### ISSUE THREAD

**Issue by BogdanaTsonevska** [reprocessing-reference/preparation#23]
Dear Catherine, 
S1 Some AUXIP PP1 CAL INS missing 
 Karen Cordier send us very complete email on S1 aux.  Did you check if the files that we mist are available as she said and did you consider them ?

**Comment by cbouzina** [comment]
Full baseline table for S1 IPF 03.31 sent to ESA today. Comments or corrections are welcome.

**Comment by cbouzina** [comment]
Mail from S1-MPC on 26nov2020:

S1B ICID 1 was active at the beginning of the mission.
In May 2019 a test was made with a new instrument configuration ICID 2 during two weeks.
At the end of the testing period, the instrument configuration was rolled back to ICID 1.
20190528T084300 is the date identifying the end of usage of ICID 2.
It is aligned on the SAR instrument stop time provided by Sentinel-1 Spacecraft Operations Manager in his report S1B-UNA-2019/0022. No product has been acquired with ICID 2 after this date.
 
The same test was performed on S1A in March 2019.
The date of the rollback from ICID 7 to ICID 6 is 20190312T092500.

The AUX_SCS (Simulated Cross Spectra) to be used are : 
S1__AUX_SCS_V20140402T000000_G20160413T103855 – application 20140402T000000-20140406T133000
S1__AUX_SCS_V20140406T133000_G20200623T142050 – application 20140406T133000-21000101T000000
to be discarded :
S1__AUX_SCS_V20171017T080000_G20171016T150910
S1__AUX_SCS_V20150722T120000_G20160413T105410
S1__AUX_SCS_V20150519T120000_G20160413T105253

For the platform and the ICID at the time of the acquisition, the selection rule uses the last ADF generated for which the validity date is before the acquisition date.
This rule applies to AUX_INS, AUX_CAL, AUX_PP1, AUX_PP2, AUX_SCS.
 
AUX_SCS does not depend on ICID so, as the last one was generated on 23/06/2020, it is the one selected for products acquired after 06/04/2014.
For products acquired before this date, the one to be used is the one generated on 13/04/2016.
However, there were no products acquired in that early period and, even if there were, products acquired before September 2014 are not made available to end users.
