### ISSUE TITLE
Question on the key for the "Attribute" in the auxip odata interface

### ISSUE THREAD

**Issue by yannick-peyrotau** [reprocessing-reference/preparation#27]
The key for the "Attribute" in the auxip odata interface is the 'Name', however since it is a collection each attribute should have a unique identifier. How do you plain to have multiple products having the same attribute names ? As it is it will not work. 
For example if you have two products A1 and A2 having both an attribute "platformShortName" then they will both share the same attribute since the key is "platformShortName". You can't have A1("platformShortName")=S2A and A2("platformShortName")=S2B with this ICD youcan only have A1("platformShortName")=A2("platformShortName")=S2A

**Comment by BogdanaTsonevska** [comment]
the attributes are expressed as an array. I will send you in a mail an example .

**Comment by BenEsquis** [comment]
Dear Bogdana,

Then there is an issue as the Attributes can not be NavigationProperty but simply properties.
NavigationProperties can't have twice the same key among all products.

I'll show you the issue in an example. But I think it is just the APPENDIX A ODATA METADATA DESCRIPTION that is not correct.

According to the example you provided I will make a new version on my side and submit it to you.

Regards

**Comment by BogdanaTsonevska** [comment]
Thanks, I will transfer you email to my colleague. 
Regards,
Bogdana

**Comment by BogdanaTsonevska** [comment]
In dead it shouldn't be a navigation property, just a property



From:   Bogdana Tsonevska/esrin/ESA
To:     "reprocessing-reference/preparation" 
<reply@reply.github.com>
Cc:     "Assign" <assign@noreply.github.com>, 
"reprocessing-reference/preparation" <preparation@noreply.github.com>
Date:   09/12/2020 10:05
Subject:        Re: [reprocessing-reference/preparation] Question on the 
key for the "Attribute" in the auxip odata interface (#27)


Thanks, I will transfer you email to my colleague. 
Regards,
Bogdana
