### ISSUE TITLE
Baseline Tag for S3 in reprocessing baseline API

### ISSUE THREAD

**Issue by BenEsquis** [reprocessing-reference/preparation#29]
The table in the user manual has several possiblity for the baseline tag.

What do we have to put in the API ?

Regards

![Image collée à 2020-12-16 10-41.png](https://images.zenhubusercontent.com/5f8021dc20042c34dcd49bca/93bf9188-d8d1-4457-b000-e9246e1107d9)

**Comment by BogdanaTsonevska** [comment]
Both because they are for two satellites  A and B. 
thanks

**Comment by BenEsquis** [comment]
I don't understand:

Do we put '06.19' or 'S3A-2.69 & S3B-1.45'

Regards

**Comment by BogdanaTsonevska** [comment]
In the previous we had just IPF version 06.19, for S3 in addition we have the configuration S3A-2.69 & S3B-1.45. 
May be if we put baseline in the past we should rename it in IPF version to avoid confusion.
Could we have both IPF version and Baseline for S3?

**Comment by BenEsquis** [comment]
Normally a baseline version is directly linked to an IPF version so the information might seems duplicated. 

We can have both IPF Version and baseline in the API if you want.

**Comment by BogdanaTsonevska** [comment]
I prefer to keep them both. Thank you.
