### ISSUE TITLE
Particular cases in SensingApplication computation

### ISSUE THREAD

**Issue by BenEsquis** [reprocessing-reference/preparation#31]
For most of the file type the creation_date, validity_start and validity_stop are correctly filled.
However for some file_types these are completely false, thus the computation of the sensingApplicability is incorrect.

Before computing a filter is done to remove doublons :
If files have the same validity_start/validity_stop then we keep only the most recently generated

SX_XXXX_XXXXX_XXXXX_20191231T184206_V20191231T145108_20191231T180838.EOF
SX_XXXX_XXXXX_XXXXX_20191231T185423_V20191231T145108_20191231T180838.EOF
SX_XXXX_XXXXX_XXXXX_20191231T200457_V20191231T145108_20191231T180838.EOF --> only this one is kept

Then we sort files by ascending validity start and compute the sensingApplication :

SX_XXXX_XXXXX_XXXXX_20191231T164448_V20191231T113339_20191231T145109.EOF
--> 2019-12-31T11:33:39.000000Z : 2019-12-31T13:12:24.000000Z
SX_XXXX_XXXXX_XXXXX_20191231T170454_V20191231T131224_20191231T162954.EOF

However some files are incorrect in the date tags:
For example ERRMAT have all their validity_start at the same time but a different validity stop.

What does that means for the SensingApplicability to be put ?

S1B_OPER_AMH_ERRMAT_MPC__20160323T080000_V20000101T000000_20160322T230000.EOF.json
S1B_OPER_AMH_ERRMAT_MPC__20161006T135743_V20000101T000000_20161005T235240.EOF.json
S1B_OPER_AMH_ERRMAT_MPC__20161007T074854_V20000101T000000_20161006T225504.EOF.json
S1B_OPER_AMH_ERRMAT_MPC__20161008T040015_V20000101T000000_20161007T233613.EOF.json
S1B_OPER_AMH_ERRMAT_MPC__20161009T040016_V20000101T000000_20161008T201005.EOF.json
S1B_OPER_AMH_ERRMAT_MPC__20161010T040015_V20000101T000000_20161009T231945.EOF.json
S1B_OPER_AMH_ERRMAT_MPC__20161011T040014_V20000101T000000_20161010T222209.EOF.json
S1B_OPER_AMH_ERRMAT_MPC__20161012T040017_V20000101T000000_20161011T235216.EOF.json

Regards

**Comment by BogdanaTsonevska** [comment]
Email sent to S1 MPC for clarification.

**Comment by cbouzina** [comment]
From bogdana.tsonevska@esa.int on 17dec2020:
For the Error Matrices (S1 ERRMAT), the selection rule is ClosestStopValidity as their validity start dates are identical. 
Concerning the ClosestStopValidity rule:
The ERRMAT file to use is the one whose validity stop date is the closest from the middle of the considered acquisition.
This validity stop date can be before or after the acquisition.
If two ERRMAT files have the same validity stop date, the last generated one should be used.
So the filter to remove doublons seems OK.

**Comment by BogdanaTsonevska** [comment]
Before computing a filter is done to remove doublons :
If files have the same validity_start/validity_stop then we keep only the most recently generated

SX_XXXX_XXXXX_XXXXX_20191231T184206_V20191231T145108_20191231T180838.EOF
SX_XXXX_XXXXX_XXXXX_20191231T185423_V20191231T145108_20191231T180838.EOF
SX_XXXX_XXXXX_XXXXX_20191231T200457_V20191231T145108_20191231T180838.EOF --> only this one is kept

Dear all in the cloud all the files are kept. Only doublons with the same creation date should be removed from the cloud
 We need to have all the historic aux data. 
In the Reprocessing configuration baseline only the recently generated file is shown.
