### ISSUE TITLE
RMO files have the same ValidityStart and ValidityStop

### ISSUE THREAD

**Issue by BenEsquis** [reprocessing-reference/preparation#34]
Dear,

After running our completion script we found out that the RMO files have the the ValidityStart and validityStop, hence making them valid only for this particular date and hour. 
Our script then doesn't understand and emit a lot of rule violations.
for example:
S3__SR_2_RMO_AX_20160420T120000_20160420T120000_20160510T234740___________________CNE_O_NT_001.SEN3.zip : Start 20160420T120000 Stop 20160420T120000

After some enquiries catherine found out that the tasktable was adding a 12 hours extend to this date.

So what is the validity computation rule for these particular files ? Do we add this 12 hours window or do we do as the ERRMAT case by taking the next file's validStart as the end of the validity ?

Regards

**Comment by BogdanaTsonevska** [comment]
email send to S3 T.O.

**Comment by BogdanaTsonevska** [comment]
Could you tell me if the average start time of the next file is more or is less than 12h? 
Regards,
Bogdana

**Comment by BenEsquis** [comment]
It seems to be 6 hours between each files

**Comment by cbouzina** [comment]
Yes, there is one file at 00:00, 06:00, 12:00 and 18:00

**Comment by BenEsquis** [comment]
Dear,

The correction done is to put a -6h and +6h on the ValidStart/ValidStop and compute the SensingApplicability based on this change.

The completion test does report some gap but only 2.
