### ISSUE TITLE
SR_2_POL have all the ValidityStart to 19870101T000000

### ISSUE THREAD

**Issue by BenEsquis** [reprocessing-reference/preparation#35]
Dear,

SR_2_POL have all the ValidityStart to 19870101T000000 thus the computation of the SensingApplicability can not be done as for the other type.

I suggest as a first approach to compute it on the same way as for the ERRMAT type ?

Regards

**Comment by BenEsquis** [comment]
Also catherine told me that this file is incremental thus the last contains the informations from the first adn so on.

Is it possible then to put only the last one and make it valid for the whole satellite period ?

Regards

**Comment by BogdanaTsonevska** [comment]
Email from S3 MPC send on 14/01/2021.
