### ISSUE TITLE
SR_1_USO_AX files have strange naming conventions

### ISSUE THREAD

**Issue by BenEsquis** [reprocessing-reference/preparation#36]
Dear,

It seems that that the USO files have strange naming convention. it seems that they inverted the ValidityStart with the CreationDate.

S3A_SR_1_USO_AX_20160223T195017_20160326T021738_20160326T084738___________________CNE_O_AL_001.SEN3.zip
S3A_SR_1_USO_AX_20160223T195017_20160327T015126_20160327T084649___________________CNE_O_AL_001.SEN3.zip
S3A_SR_1_USO_AX_20160223T195017_20160328T012505_20160328T084726___________________CNE_O_AL_001.SEN3.zip
S3A_SR_1_USO_AX_20160223T195017_20160329T005844_20160329T084837___________________CNE_O_AL_001.SEN3.zip
S3A_SR_1_USO_AX_20160223T195017_20160330T021420_20160330T084640___________________CNE_O_AL_001.SEN3.zip

Using the ERRMAT computation method we still have a few gap.
Do you know what are the applicability date for these files ?

Regards

**Comment by BogdanaTsonevska** [comment]
Email sent to S3 T.O,

**Comment by BogdanaTsonevska** [comment]
Email from S3 MPC send on 14/01/2021.
