### ISSUE TITLE
Missing S1 ICE, WND, WAV

### ISSUE THREAD

**Issue by BogdanaTsonevska** [reprocessing-reference/preparation#37]
Could I ask you to download from the Openhub the level 2 corresponding to the period for which the S1__AUX_ICE,S1__AUX_WND, S1__AUX_WAV are missing. The L2 contain the aux files that were used for the generation. Afterwards check if the generated products were in reality generated with the auxiliary products that we think should be used or if there were generated with other aux files. 
Thank you .
After this analysis we will decide how to deal with the missing files. 
Note: Ignore the 2013 (lanching date S1 3 April 2014 S1B 25 April 2016)

**Comment by cbouzina** [comment]
There is no S1 L2 products of 2014 available on the Copernicus Hub.
The following 4 OCN products have been selected during gaps in AUX files continuity.

For S1A_WV_OCN__2SSV_20150215T131327_20150215T131330:
            <safe:resource name="S1__AUX_WND_V20150215T030000_G20150215T063112.SAFE" role="AUX_WND"/>
            <safe:resource name="S1__AUX_ICE_V20150212T120000_G20150213T042713.SAFE" role="AUX_ICE"/>
            <safe:resource name="S1__AUX_WAV_V20150206T060000_G20150201T171331.SAFE" role="AUX_WAV"/>

For S1A_WV_OCN__2SSV_20150221T154207_20150221T154210:
            <safe:resource name="S1__AUX_WND_V20150221T090000_G20150221T064503.SAFE" role="AUX_WND"/>
            <safe:resource name="S1__AUX_ICE_V20150219T120000_G20150220T043734.SAFE" role="AUX_ICE"/>
            <safe:resource name="S1__AUX_WAV_V20150206T060000_G20150201T171331.SAFE" role="AUX_WAV"/>

For S1A_WV_OCN__2SSH_20150303T141940_20150303T141942:
            <safe:resource name="S1__AUX_WND_V20150303T060000_G20150303T065229.SAFE" role="AUX_WND"/>
            <safe:resource name="S1__AUX_ICE_V20150227T120000_G20150228T043257.SAFE" role="AUX_ICE"/>
            <safe:resource name="S1__AUX_WAV_V20150213T030000_G20150227T100339.SAFE" role="AUX_WAV"/>

For S1A_IW_OCN__2SDV_20200101T112121_20200101T112150:
            <safe:resource name="S1__AUX_WND_V20200101T120000_G20200101T055102.SAFE" role="AUX_WND"/>
            <safe:resource name="S1__AUX_ICE_V20191231T120000_G20200101T043826.SAFE" role="AUX_ICE"/>
            <safe:resource name="S1__AUX_WAV_V20191231T210000_G20191226T154608.SAFE" role="AUX_WAV"/>

Considering that AUX_ICE is produced every 24h, AUX_WAV and AUX_WND every 3h, none of these 4 OCN products has got the correct AUX files, but older ones (up to 20 days older).

**Comment by BogdanaTsonevska** [comment]
There is no possibility to obtain the auxiliary; the Reprocessing Data Configuration will select the files as it was done in the past considering the selection rules. This should be included like an explanation even at the  S1 Configuration Baseline UM.

**Comment by cbouzina** [comment]
Here is my conclusion/explanation to be included in the User Manual:
The precise orbit ADF (AUX_POEORB) are not available for the commissioning phases of S1A (april-september 2014) and S1B (april-september 2016).
Also, many AUX_WND, AUX_WAV, AUX_ICE files are missing for 2014, so no reprocessing action is possible for 2014.
A few AUX_WND, AUX_WAV, AUX_ICE files are missing in 2015 and 2016, but the reprocessing system can use the last previous available file.

**Comment by BogdanaTsonevska** [comment]
Perfect, maybe to say: "no reprocessing action is possible for the commissioning phase for 2014. "
Thank you.
