### ISSUE TITLE
S1 ICID

### ISSUE THREAD

**Issue by BogdanaTsonevska** [reprocessing-reference/preparation#42]
The ICID shall be considered in the Reprocessing Configuration Database.
The User Manual shall explain that.

**Comment by cbouzina** [comment]
Please, provide the official explicative text for the Sentinel-1 ICID.
(No explanation is found on https://qc.sentinel1.copernicus.eu/)

**Comment by cbouzina** [comment]
As no official definition of the ICID and its use is available, the mail from S1-MPC is used for basic explanation in the User Manual.

**Comment by BogdanaTsonevska** [comment]
There is a misunderstanding I read in the User Manual : 
This old configuration back into operation is not possible for the system. One solution could be to create new ADF with corresponding 2019 validity start: this is recommended in the S1 PDGS for the sake of consistency and clarity. For now, a trick is implemented in the system to support this anomaly: the concerned ADF are referenced twice, with their current validity start and with the 2019 reactivation dates.
So if a trick is implemented does it mean that you don't use the ICID for the files selection?
