### ISSUE TITLE
S3 IPF updates

### ISSUE THREAD

**Issue by BogdanaTsonevska** [reprocessing-reference/preparation#43]
S3 IPF will be updated in April. CS will take them into account in May. 
Next delivery is in December. CS will take them into account in Janualry 2022.

**Comment by BogdanaTsonevska** [comment]
In the Case of S2, is it possible to take into account a new baseline in min 2 weeks ?

**Comment by cbouzina** [comment]
I think 3 weeks is more realistic, as we will have to update all documentation and rerun the tests.
I would prefer to redeliver all the current baselines with the last corrections,
before going into the new IPF versions.

**Comment by cbouzina** [comment]
IPF update is done.
