### ISSUE TITLE
AUXIP Metrics clarification

### ISSUE THREAD

**Issue by BenEsquis** [reprocessing-reference/preparation#46]
Dear,

In 5.1.2Auxiliary DataDeliveryInterface PointsMetrics many metrics are requested.

What is the list of <productType> needed to be listed ? Is it the list of aux type in ALL_Aux.xlsx ?
What is the meaning of platformSerialIdentifier ? Is this A/B ?

Regards

**Comment by BogdanaTsonevska** [comment]
Dear Benjamin, 

those metrics  are for the monitoring, that means number of product published, the volume of the files. You don't have this information in the All_Aux it is what is currently published on AUXIP. May be you can come to the weekly meeting so I can try to explain better if I am not clear. 


platformSerialIdentifier is A/B ?

**Comment by BenEsquis** [comment]
Clarified during a meeting
