### ISSUE TITLE
Missing Aux files for S3 compliteness tests

### ISSUE THREAD

**Issue by BogdanaTsonevska** [reprocessing-reference/preparation#47]
Dear Catherine, 
Could you please check for this sensing time if we have on DataHub the products related to the two missing files and see which auxiliaries were used to generate those files? 
Thank you in advance
S3__SR_2_RMO_AX_20160330T180000_20160330T180000_20160420T114742
S3A_SR___POEPAX_20170115T215942_20170116T235942_20170210T071647

Thank you in advance for your help
Regards,
Bogdana

**Comment by cbouzina** [comment]
OK, I will do that next week because I am following a Python course this week.

**Comment by cbouzina** [comment]
Considered gap: S3__SR_2_RMO_AX_20160324T180000_20160324T180000_20160414T114751___________________CNE_O_NT_001.SEN3.zip - S3__SR_2_RMO_AX_20160330T180000_20160330T180000_20160420T114742___________________CNE_O_NT_001.SEN3.zip : 2016-03-25T00:00 - 2016-03-30T12:00 not covered
Downloaded product on SciHub : S3A_SR_2_LAN____20160327T004524_20160327T013128_20180518T223435_2764_002_202______LR1_R_NT_003.SEN3
This product used :
-<sentinel-safe:resource role="SRAL Ocean barotropic correction (MOG2D data)" name="S3__SR_2_RMO_AX_20160327T000000_20160327T000000_20160416T114704___________________CNE_O_ST_001.SEN3">
-<sentinel-safe:resource role="SRAL Ocean barotropic correction (MOG2D data)" name="S3__SR_2_RMO_AX_20160327T060000_20160327T060000_20160416T234858___________________CNE_O_ST_001.SEN3">


Considered gap: 
S3A_SR___POEPAX_20170113T215942_20170114T235942_20170208T071436___________________POD_O_NT_001.SEN3.zip - S3A_SR___POEPAX_20170115T215942_20170116T235942_20170210T071647___________________POD_O_NT_001.SEN3.zip : 2017-01-14T23:59:42 - 2017-01-15T21:59:42 not covered
Downloaded product on SciHub : 
S3A_SR_2_LAN____20170115T111500_20170115T120529_20180519T204848_3029_013_165______LR1_R_NT_003.SEN3
No POEPAX is used.

**Comment by BogdanaTsonevska** [comment]
Shall we mentioned this in the UM?

**Comment by cbouzina** [comment]
Last time, we decided to provide the list of missing ADF as a separate page.
But I can add it as annex to the User Manual.

**Comment by cbouzina** [comment]
Note that the RMO files exist somewhere as they have been used in production, but where ???

**Comment by BogdanaTsonevska** [comment]
I asked for redelivery because S3  T.O.  told me that now a lot of these files are transferred from PDGS to the LTA.

**Comment by yannick-peyrotau** [comment]
@BogdanaTsonevska S2 ? this ticket is about S3 right ?

**Comment by BogdanaTsonevska** [comment]
Sorry, yes S3

**Comment by cbouzina** [comment]
For the following missing ADF:
S3B_OL_1_CAL_AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002.SEN3
S3B_OL_1_EO__AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002.SEN3
S3B_OL_1_INS_AX_20180425T000000_20180617T235959_20180621T120000___________________MPC_O_AL_002.SEN3 
I am trying to download a S3B OLCI L1 product of 17 june 2018.
My request is pending on SciHub...

**Comment by cbouzina** [comment]
I managed to download 3 S3B OLCI L1 products of 17 june 2018 from DHUS.
Each product zip file contains only one nc file and this nc file seems corrupted.

**Comment by BogdanaTsonevska** [comment]
Thank you, could you please explain that these products could not be re-processed due to anomaly. 
I will try to speak to Jordi about this. 
Do you have any advice on how to deal with the problem?

**Comment by cbouzina** [comment]
I cannot explain the problem. 
Please inform S3 PDGS that all S3B OLCI L1 products of 17 june 2018 seem corrupted.
Maybe these data are not really available because they come from commissioning phase ?

**Comment by BogdanaTsonevska** [comment]
yes, I will. The commissioning should be the reason. we could put this as an explanation.

**Comment by cbouzina** [comment]
Also, we shoud not forget about the necessary list of S3A_OL_1_CAL_AX (see mail exchange on 14 december 2020). 
About the S3B_OL_1_CAL_AX list, I am not so sure anymore because the list I used is different from the one used in the OLCI reprocessing report. Therefore, if possible, ESA should provide both lists (S3A and S3B).

**Comment by BogdanaTsonevska** [comment]
Please download from the LTA AIP the R03.
I have sent an email to S3 T.O. On the documentation baseline on 27/05. today I will send him a reminder.

**Comment by BogdanaTsonevska** [comment]
sorry my email to you was returned: 

Please download from the LTA AIP the R03.

**Comment by cbouzina** [comment]
Just a reminder that we need the list of S3A and S3B OL_1_CAL necessary for reprocessing campaign.

**Comment by cbouzina** [comment]
The lists have never been provided.
