### ISSUE TITLE
Odata attributes extraction : no software name/version found in manifest files of .SAFE S1 aux files.

### ISSUE THREAD

**Issue by nmeskini** [reprocessing-reference/preparation#49]
Hi Bogdana ,

I came across an issue while extracting Odata attributes, it's concern auxiliary S1 data files  the ".SAFE" ones ,  it's expected that one could be able to extract 'ProcessorName' and 'ProcessorVersion' tags from the manifest file (in safe:processing/safe:software corresponding tag ) as explained in the document "Sentinel-1 Product Attributes Mapping_v1.3.xlsx",  But in all .SAFE files there is no "software" tag in the processing unit ( safe:processing )

Regards,

Naceur MESKINI from cs team.

**Comment by cbouzina** [comment]
After checking several S1 products, I could not find any manifest file where these tags are empty.
So this is a rare problem, which is anyway under ESA responsibility.
Therefore, this is out of the scope of this activity.
