### ISSUE TITLE
ParallelDownloadsQuota : Maximum number of separate downloads which can be performed in Parallel

### ISSUE THREAD

**Issue by nmeskini** [reprocessing-reference/preparation#50]
Hi Bogdana,

We need clarification about how to deal with auxip service downloads quotas, especially for “ParallelDownloadsQuota”( Maximum number of separate downloads which can be performed in Parallel )
The problem is that for each $value request sent by client to download a product, a storage cloud link is generated and sent to the client and the download occurs actually in the cloud side out of auxip control, these links are temporary with a validity period limited in time , so we don’t have ability to count parallel downloads.
However we can count all cloud links consecutively generated, and consider them as parallel downloads.

Best regards,

Naceur MESKINI.

**Comment by BogdanaTsonevska** [comment]
Dear Naceur, 
I agree to use the cloud links for the count on the parallel downloads. Please put a Note in the AUXIP ICD about this topic or if you think it is more suitable just in the AUXIP Compliance Report.
Regards,
Bogdana

**Comment by cbouzina** [comment]
Dear Naceur, 
could you please add this information in RPP-API-0014-CS_Reprocessing_Data_Baseline_API_ICD ?
Counting method and Max per user account.
Thanks

**Comment by nmeskini** [comment]
Dear all,

This information is already provided in the following AUXIP ICD document , see 2.7 Quotas section.
RRPP-API-0008-CS_Reprocessing_Auxiliary_Files_Interface.

Regards,

**Comment by cbouzina** [comment]
Doc is OK.
