### ISSUE TITLE
Subscriptions and Roles

### ISSUE THREAD

**Issue by nmeskini** [reprocessing-reference/preparation#52]
Hi Bogdana, 

I am wondering which role should have a client to be able to create / manage Subscriptions ?

Best Regards,

Naceur MESKINI

**Comment by BogdanaTsonevska** [comment]
Dear Nacuer,
I discovered just now the topic.  I don't think that client should be able to manage Subscriptions. Yannick told me that the subscription is open for the moment, may be there should be some kind of validation fromo you in the future. 
Bogdana

**Comment by yannick-peyrotau** [comment]
Hi Bogdana,

No problem.
It is just a configuration to change the registration "procedure".
We are able to add a manual validation when it will be needed.

Regards,
Yannick Peyrotau

**Comment by cbouzina** [comment]
It is decided that any subscription is possible for any user account. Is it OK ?

**Comment by cbouzina** [comment]
OK from ESA in progress meeting of today.
