### ISSUE TITLE
S2 CAMS data

### ISSUE THREAD

**Issue by cbouzina** [reprocessing-reference/preparation#53]
I read the new documentation for future ECMWF and CAMS data.
If I understood well our meeting discussion yesterday, only CAMS analysis data should be considered in our context:
AUX_CAMSAN (AUX_CAMSFO and AUX_CAMSRE are out of scope).
The selection rule for ECMWF data is LatestValCover. Should we use the same for CAMS data ?

**Comment by cbouzina** [comment]
From:        "Olivier Colin" <Olivier.Colin@esa.int>
To:        "Bogdana Tsonevska" <bogdana.tsonevska@esa.int>
Cc:        "Fernando Moccia" <Fernando.Moccia@esa.int>
Date:        16-04-21 11:10 AM
Subject:        Fwd: ESA-EOPG-EOPGC-TN-42 delivery

Salut Bogdana

I wanted to point out that Fernando's doc is also relevant to CS’s activity with Catherine Bouzinac for the repro preparation.
It describes 3 types of auxiliary data files that CS will need to create from the ECMWF APIs:

- ECMWF forecast (AUX_ECMWFD) with the new variables and new format, on the basis of source data to be recovered from ECMWF’s MARS API
- CAMS analysis (AUX_CAMSAN), on the basis of source data to be recovered from ECMWF's CAMS API
- CAMS reanalysis (AUX_CAMSRE), on the basis of source data to be recovered from ECMWF's CAMS API

For ECMWF, all needs to be recovered from start of mission in 2015
For the two CAMS we will need to recover all available reanalysis data (preferred), else the analysis data, from start of mission up to now. I.e. we need to be covered by one of he two with preference on the reanalysis. We will probably not find the reanalysis available up the recent times but we will then be able to cover up with the analysis.

I guess this is enough to trigger the activity with Catherine, please let me know otherwise obviously we’ll be there in support.

cheers!
Olivier

**Comment by cbouzina** [comment]
From Olivier's mail above, I correct my first comment:
only CAMS analysis and reanalysis data should be considered in our context:
AUX_CAMSAN and AUX_CAMSRE (AUX_CAMSFO are out of scope).
The selection rule for ECMWF data is LatestValCover. Should we use the same for CAMS data ?

**Comment by BogdanaTsonevska** [comment]
email sent to Olivier

**Comment by BogdanaTsonevska** [comment]
Dear Bogdana,
We have analysed the selection rules for the CAMS file and the following selection rule shall be applied in the following order:
- LatestValCover
- in case both Re-analysis and analysis file are available only one type shall be selected with the following priority: 1 Re-analysis, 2 Analysis

Regards,

Fernando

**Comment by cbouzina** [comment]
OK. Many thanks.
