### ISSUE TITLE
Make all reprocessing preparation package services ( task 1,2 and 3) share the same users database ?

### ISSUE THREAD

**Issue by nmeskini** [reprocessing-reference/preparation#56]
Hi Bogdana,

We are wondering if we can make all services of the Reprocessing Preparation Package ( Reprocessing Configuration Baseline, Auxip, Reprocessing Data Baseline )  sharing the same users database,in fact, this would allow clients to avoid creating several accounts and also it would facilitate the implementation of the task 3 since it uses tasks 1 and 2.
By sharing the same users database, a client can therefore access to all services with the same token. 

Best Regards,

Naceur.

**Comment by cbouzina** [comment]
The same user account can use all the services.
