### ISSUE TITLE
Selection rules of the TASK3 and time interval [t0 – Δ0 , t1 + Δ1]  

### ISSUE THREAD

**Issue by nmeskini** [reprocessing-reference/preparation#57]
Hi Bogdana,

To be able to apply selection rules of the TASK3 , some parameters defining the selection time interval [t0 – Δ0 , t1 + Δ1] are needed. 
where :
t0 and t1 are the values set into the “Start” and “Stop” validity tags
Δ0 and Δ1 are the values set into the T0, T1 tags of the Task Table

We suppose that t0 and t1 can be retrieved from the L0 product name, however we don't know how to get Δ0 and Δ1 ?

Best Regards,
Naceur MESKINI.

**Comment by BogdanaTsonevska** [comment]
Hi, 
I will provide you the TT  for S3 (I asked permission again) or I will give you a table with the T0 and T1. Do you have the same issue with S1 and S2, are they 0? 
Regards,
Bogdana

**Comment by cbouzina** [comment]
Information from ESRIN yesterday :
For Sentinel-3, the default values for Δ0 and Δ1 come from the current Task Tables, but they can be modified by the user or in case of new TT version.

**Comment by cbouzina** [comment]
The values from the TT provided by ESA have been added in the data base.
Note that the user cannot change them.
Only the administrator can modify these values in the data base.

**Comment by cbouzina** [comment]
This is OK.
