### ISSUE TITLE
 We face an issue with S2 Level 0 products. validity stop date t1 is missing !

### ISSUE THREAD

**Issue by nmeskini** [reprocessing-reference/preparation#58]
Hi Bogdana, 

Names of S2 L0 products contains only the validity start date t0, and the creation date, 
So without the validity stop date  we won't be able to apply the selection rules , especially the 
LatestValCover rule needed for many S2 auxiliary data files.

Regards,

Naceur MESKINI.

**Comment by cbouzina** [comment]
The chosen and implemented solution is t1 = t0
