### ISSUE TITLE
Task 3 for  S3SYN mission

### ISSUE THREAD

**Issue by nmeskini** [reprocessing-reference/preparation#59]
Hi Bogdana, 
As requested, the Task 3 service needs level 0 products names to be working, this causes an issue with S3SYN mission that  is based on the level 1 products OLCI and SLSTR ( there is no L0 for S3SYN ) .

We suggest to use OLCI L0 products names for S3SYN mission, since names of L0 products are only used to retrieve the validity start and validity stop.
With other parameters, mission,unit and product_type  we are able to retrieve the right applicable aux data files for the given mission. 

Regards,
Naceur MESKINI.

**Comment by cbouzina** [comment]
This is agreed and done.
